### ISSUE TITLE
UI could be improved with a loading modal on click

### ISSUE THREAD

**Issue by mudarthc** [TriageCapacityPlanning/Testable-Artifiact#1]
Bug : User gets no feedback once button clicked, the dont know that something is loading. (usability issue)
Steps: 

https://drive.google.com/file/d/163sFYI9WYtcm5-hy9gcL4NwdEETnA9O2/view?usp=sharing

Environment: Mac OS

Expected: Expected some sort of feedback either error or loading modal when button clicked 

Actual: No feedback, user just needs to wait for chart to appear, this can be confusing especially for a new user

**Comment by SEsseltine** [comment]
Fixed in most recent UI
