### ISSUE TITLE
Successful build message is different as in Testable_Artifact

### ISSUE THREAD

**Issue by lim147** [TriageCapacityPlanning/Testable-Artifiact#10]
When I built the project successfully, I didn't saw the message `ml exited with code 0` as specified in the Testable Artifact, instead, I saw this:
<img width="426" alt="Screen Shot 2021-02-25 at 3 39 23 PM" src="https://user-images.githubusercontent.com/35234798/109215533-46f6d480-7781-11eb-9344-c015c7a42b15.png">

**Comment by SEsseltine** [comment]
This documentation was for external testing purposes only, will be addressed for deployment. Valid doc error for docs provided.
