### ISSUE TITLE
Upload File Success/Fail?

### ISSUE THREAD

**Issue by lim147** [TriageCapacityPlanning/Testable-Artifiact#12]
It's hard to tell whether the file is uploaded successfully or not since there is no UI change on the page. Maybe add a message to specify when it's finished uploading.
<img width="793" alt="Screen Shot 2021-02-25 at 4 05 38 PM" src="https://user-images.githubusercontent.com/35234798/109217053-4eb77880-7783-11eb-94e4-ac5e39c2a117.png">

**Comment by SEsseltine** [comment]
Duplicate: #3
