### ISSUE TITLE
Prediction form doesn't show validation errors

### ISSUE THREAD

**Issue by coffeexcode** [TriageCapacityPlanning/Testable-Artifiact#15]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
1. Start application
2. Navigate to interval prediction
3. Fill in 50% for confidence, 50% for number of simulations, and pick 1 date for the interval

### Expected:
There should be an on the date picker field

### Actual:
No error is displayed

### Screenshot:
![image](https://user-images.githubusercontent.com/13461008/109368999-e347d680-7868-11eb-96c6-52c10a211aec.png)

**Comment by SEsseltine** [comment]
@Rubinstd I believe that you've already fixed this but can you please verify the entirety of this ticket is fixed?

**Comment by Rubinstd** [comment]
This has been fixed with updated form validation.
