### ISSUE TITLE
Invalid form can be submitted for interval prediction

### ISSUE THREAD

**Issue by coffeexcode** [TriageCapacityPlanning/Testable-Artifiact#16]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
1. Start application
2. Navigate to "interval-prediction"
3. Select only 1 date
4. Hit submit

### Expected:
There should be form errors shown and the form should bot submit

### Actual:
The form is submitted despite being invalid

### Screenshot:
![image](https://user-images.githubusercontent.com/13461008/109369571-d1673300-786a-11eb-8055-ad32019df40b.png)

**Comment by SEsseltine** [comment]
fixed
