### ISSUE TITLE
Refreshing page changes visual style of elements

### ISSUE THREAD

**Issue by coffeexcode** [TriageCapacityPlanning/Testable-Artifiact#17]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
1. Start application
2. Navigate to "Admin: Clinic 1"
3. Refresh page

### Expected:
The page should look exactly the same

### Actual:
Input elements change style

#### Before
![image](https://user-images.githubusercontent.com/13461008/109369588-e47a0300-786a-11eb-8693-08e45b60e9bb.png)

#### After
![image](https://user-images.githubusercontent.com/13461008/109369600-efcd2e80-786a-11eb-8948-e96e4095a678.png)

**Comment by trevorNgo** [comment]
@SEsseltine reproduction steps are incorrect here though...

**Comment by SEsseltine** [comment]
> @SEsseltine reproduction steps are incorrect here though...

@trevorNgo 

Reproduction steps from #30 are a subset of these reproduction steps. Steps 1 and 2 from this bug equate to the steps from #30 and then the bug's validity is verified with the refreshing component of the reproduction steps.

**Comment by trevorNgo** [comment]
Try it now. Load up the app, navigate to admin page. The correct CSS will always be applied.

**Comment by trevorNgo** [comment]
The bug only manifests with a specific order of user navigation. The user must load up the predict-interval page first, which is the culprit. If not, this bug won't manifest itself.

**Comment by trevorNgo** [comment]
@KristieTom12

**Comment by SEsseltine** [comment]
Fixed
