### ISSUE TITLE
Improper validation on "Number of Simulations"

### ISSUE THREAD

**Issue by coffeexcode** [TriageCapacityPlanning/Testable-Artifiact#18]
### Severity
Low

### Environment
Windows 10 Desktop
Chrome

### Steps to reproduce:
1. Start application
2. Navigate to "Interval Prediction"
3. Select a valid date range and confidence interval
4. Select 800
5. Hit submit

### Expected:
The form should say that this value is invalid

### Actual:
Submits and runs without issue

### Additional
The validation looks like it's actually 0-1000 instead of 0-100

### Too large (with no error)
![image](https://user-images.githubusercontent.com/13461008/109369844-1dff3e00-786c-11eb-950f-a499f818eab5.png)

#### Too large (with error)
![image](https://user-images.githubusercontent.com/13461008/109369811-fc9e5200-786b-11eb-8736-8b47bbb17c59.png)

**Comment by SEsseltine** [comment]
fixed, this field has been removed
