### ISSUE TITLE
Enhancement Request: Add a loading indicator when prediction is running

### ISSUE THREAD

**Issue by coffeexcode** [TriageCapacityPlanning/Testable-Artifiact#19]
When a user submits a interval prediction, the resulting action is very long running. There is no UI element indicating that something is happening which may result in multiple form submissions furthering the loading delay. For example, with 2 short intervals and 75 simulations, the request time was approximately 11 seconds and there was no indication that what I submitted was working.

A simple loading element would greatly improve user satisfaction.
Following the material design specifications: [https://material.io/archive/guidelines/components/progress-activity.html#progress-activity-types-of-indicators](https://material.io/archive/guidelines/components/progress-activity.html#progress-activity-types-of-indicators)

Request timeline: 
![image](https://user-images.githubusercontent.com/13461008/109370136-155b3780-786d-11eb-97fb-9b7a0b104ceb.png)

**Comment by SEsseltine** [comment]
Fixed.
