### ISSUE TITLE
Not obvious that triage class can be edited

### ISSUE THREAD

**Issue by mudarthc** [TriageCapacityPlanning/Testable-Artifiact#2]
**Bug** : the UI appears to be a graph with information not obvious that the table can be edited
**Steps**: 
1. got to http://localhost:4200/interval-prediction as instructed 
2. got to "admin page"
![Screen Shot 2021-02-25 at 12 40 13 PM](https://user-images.githubusercontent.com/35268733/109193674-a09dd580-7766-11eb-939e-610a82118541.png)

**Environment**: Mac OS
**Expected**: either text explaining this or a more obvious ui, similar to this: 
![image](https://user-images.githubusercontent.com/35268733/109194061-0be7a780-7767-11eb-8fd1-2e413a9ea411.png)
or even an input box that makes it more apparent: 
![image](https://user-images.githubusercontent.com/35268733/109194173-2de12a00-7767-11eb-97b6-655412262265.png)

**Actual**: No feedback from UI that the table can be editable

**Comment by SEsseltine** [comment]
fixed, potential to adjust this screen was added as a possible future enhancement to the frontend repository but is beyond scope of this version
