### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by teemh** [TriageCapacityPlanning/Testable-Artifiact#21]
Using Ubuntu VM and FireFox. This might be a FireFox only issue. I think it's easier to disable CORS in chrome.

![image](https://user-images.githubusercontent.com/59770668/109372546-23628580-7878-11eb-87b2-288f397c1291.png)

If have a client / server setup on the same local-host, the server needs to send specific headers to the client to allow CORS

If you send these, for example, on a get request, it should work.
Access-Control-Allow-Origin: *
Access-Control-Allow-Methods: GET, POST, OPTIONS
Access-Control-Allow-Headers: Content-Type

**Comment by Rubinstd** [comment]
Are you running the components in containers by running the ```docker-compose up``` command or by running each individual component manually?

**Comment by SEsseltine** [comment]
More information was needed but seems this ticket is stale.
