### ISSUE TITLE
No Interval - Error: InvalidPipeArgument

### ISSUE THREAD

**Issue by teemh** [TriageCapacityPlanning/Testable-Artifiact#22]
Ubuntu VM + FireFox

Loaded the website and immediately hit get prediction button. No interval

![image](https://user-images.githubusercontent.com/59770668/109373024-95d46500-787a-11eb-953a-82cee8eb0671.png)

Provides the following errors:

![image](https://user-images.githubusercontent.com/59770668/109373034-a7b60800-787a-11eb-87e7-48eae3716766.png)

**Comment by SEsseltine** [comment]
fixed with form validation
