### ISSUE TITLE
Unable to type into Prediction Intervals start field

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [TriageCapacityPlanning/Testable-Artifiact#23]
Clicking into the region of the Prediction Intervals specifying the end date works as expected, with the cursor appearing as shown in the below screenshot, but clicking anywhere over the start date in the same way does not set the cursor in that position.

![image](https://user-images.githubusercontent.com/25377268/109375899-6e879300-788e-11eb-80f7-6caa36a624b6.png)

If the expected usage to get the cursor in position to specify the start date is different, or if the text and form field layout are somehow misleading, expectations from the user are not clear and this may then be considered a usability issue.

Platform: Windows
Browser: Microsoft Edge (Chromium-based)

Severity: High
Priority: High

**Comment by Sujan-Kandeepan** [comment]
Finally figured out a way to type into the starting date field: place the cursor in the ending date field as above, press the left arrow key a few times rapidly (seemingly moves an invisible cursor), and start typing to see the text begin to populate in the starting date field. It's very unintuitive due to the lack of proper visual feedback and it feels like I'm using video game cheat codes here.

**Comment by Rubinstd** [comment]
This bug has been fixed.
