### ISSUE TITLE
Arrow keys allow number of simulations to go out of range

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [TriageCapacityPlanning/Testable-Artifiact#24]
Number of simulations field expects values between 0 and 100, selection using arrow keys starts at 0 when there is no number set and it is relatively easy to enter a number out of range using the up/down arrow keys.

Expected behaviour: stop decreasing number after 0 and stop increasing number after 100.

Actual behaviour: number is allowed to arbitrarily increase or decrease (seemingly no max/min attributes set on input field).

Platform: Windows
Browser: Microsoft Edge (Chromium-based)

Severity: Low
Priority: Low

**Comment by SEsseltine** [comment]
numbers can still be entered out of range but are caught by a validator
