### ISSUE TITLE
No clear feedback/action when invalid Clinic Data file uploaded

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [TriageCapacityPlanning/Testable-Artifiact#25]
The file picker for the Clinic Data field under Admin: Clinic 1 does not restrict invalid file types. The expected file type is CSV but on the Windows Explorer file picker, for instance, the file type is set to `All files (*.*)` instead of using the custom `.csv` and when an invalid file is uploaded, there is no clear feedback or change anywhere on the page.

Platform: Windows
Browser: Microsoft Edge (Chromium-based)

Severity: Medium
Priority: Medium

**Comment by SEsseltine** [comment]
fixed
