### ISSUE TITLE
Number of triage classes stuck at 4

### ISSUE THREAD

**Issue by Sujan-Kandeepan** [TriageCapacityPlanning/Testable-Artifiact#26]
The entire triage classes table is editable in its individual values but the number of rows for distinct triage classes remains static. It may the case that, while renaming triage classes to create a new list, there may be more or fewer triage classes required. The option to add or remove rows to enable having any non-zero number of triage classes would be ideal.
![image](https://user-images.githubusercontent.com/25377268/109377802-99c4af00-789b-11eb-9a7a-e92bb9f39290.png)

Platform: Windows
Browser: Microsoft Edge (Chromium-based)

Severity: Medium
Priority: Medium

**Comment by SEsseltine** [comment]
Implemented adding new triage classes. The user is unable to remove triage classes at this time to maintain classification consistency across the system.
