### ISSUE TITLE
Inputs Not Contained Within Parent Element and unable to mobile horizontal scrolling

### ISSUE THREAD

**Issue by trevorNgo** [TriageCapacityPlanning/Testable-Artifiact#28]
Both on desktop and mobile, the input fields extend passed parent container boundaries.

![image](https://user-images.githubusercontent.com/23327878/110162144-534fe280-7dbc-11eb-84c6-b734c9ae1672.png)

Likewise on mobile the same issue occurs but as well, there is no way to horizontally scroll so you are stuck with only two columns of input:

![image](https://user-images.githubusercontent.com/23327878/110162529-dcffb000-7dbc-11eb-90b0-a40389d22acb.png)

Severity: Low-Medium
Reproduction: 
Navigate to link `http://localhost:4200/admin`
Resize window width smaller to about 1030px wide.

Chrome 89.0.4389.72 
iphone X

**Comment by SEsseltine** [comment]
new changes mean that this becomes an issue at resolutions below 875px, this should be sufficient for desktop usage and mobile is out of scope of the project
