### ISSUE TITLE
Hamburger Navigation Bar Inaccessible When Window Width Too Small

### ISSUE THREAD

**Issue by trevorNgo** [TriageCapacityPlanning/Testable-Artifiact#29]
I have my theories of why this is the case...
On my 1920x1080 screen resolution and 100% zoom, the window width smaller than 991px will immediately throw the hamburger bar to the right side of the document body, where it is no longer accessible. (with different zoom scaling, the computed max-width value changes, so not guaranteed to be 991px every time)

![image](https://user-images.githubusercontent.com/23327878/110163618-446a2f80-7dbe-11eb-8dd2-d2281e577db7.png)

Reproduction:
Load any page, such as `http://localhost:4200/admin`
Reduce width window size until hamburger bar is no longer accessible.

**Comment by SEsseltine** [comment]
fixed
