### ISSUE TITLE
Upload file saved?

### ISSUE THREAD

**Issue by mudarthc** [TriageCapacityPlanning/Testable-Artifiact#3]
**Bug**: when uploading file i get confirmation in the console "historical data uploaded", however once i click off the page to "Interval prediction" and click back, the file is no longer there. This might just be a UI feature not implemented yet or file might not be actually saved ? 

**Steps**: 
1. upload sample csv file provided 
2. click "upload" 
3. view console for confirmation 
4. click on "Interval prediction"  
5. click back to "Admin" 

**Environment**:  Mac OS

**Expected**:  Expected file to still exist

**Actual**: File no longer under Upload Data, empty

**Comment by SEsseltine** [comment]
fixed with snack bars for user feedback
