### ISSUE TITLE
Input Fields CSS Outline Not Being Applied When Navigating From Interval Prediction Page

### ISSUE THREAD

**Issue by trevorNgo** [TriageCapacityPlanning/Testable-Artifiact#30]
This bug only happens when this specific navigation from the hamburger bar occurs. Refreshing the page, or navigating to admin page from home page will have inputs' css applying properly.

Whenever switching tabs from the Interval Prediction tab found at `http://localhost:4200/interval-prediction` to the admin tab found at `http://localhost:4200/admin`, the input fields on the admin page are not outlined. 
It's important because on first run-through of the app, I did not know these fields were editable.

![image](https://user-images.githubusercontent.com/23327878/110165337-cb200c00-7dc0-11eb-9164-d57491d8484e.png)

My hypothesis, the interval-prediction page is overwriting css which gets carried forward and applied to admin page. I even identified the culprit @SEsseltine  😭

![image](https://user-images.githubusercontent.com/23327878/110165599-26ea9500-7dc1-11eb-8031-1e609a5589ac.png)

![image](https://user-images.githubusercontent.com/23327878/110165722-51d4e900-7dc1-11eb-9355-2178f3ac9e4d.png)

Severity: Medium
Reproduction:
You may load the client in any way by reaching a valid route `http://localhost:4200/[valid-route-is-optional]`
Navigate to the interval-prediction page using the hamburger navigation menu on the left.
Navigate to the admin:clinic1 page using the hamburger navigation menu.

**Comment by SEsseltine** [comment]
duplicate with #17
