### ISSUE TITLE
Unable to start ML service on Windows 10

### ISSUE THREAD

**Issue by Jailoodu** [TriageCapacityPlanning/Testable-Artifiact#31]
**Summary**: Attempted to start the application on a Windows device, and the ML service failed to start.

**Visual proof**:
![image](https://user-images.githubusercontent.com/21979292/110214047-c31fa500-7e70-11eb-948f-40129397c746.png)

**Logs**: [report.txt](https://github.com/TriageCapacityPlanning/Triage-Testable-Artifact/files/6095714/report.txt)

**Expected result**: Docker Compose shows that app has been successfully compiled, the API has debug mode initialized and the ML service has exited with code 0.

**Actual result**: ML service has exited with code 100. Not able to access `http://localhost:4200/interval-prediction`.

**Steps to reproduce**:

1. Ran the command `git clone https://github.com/TriageCapacityPlanning/Triage-Testable-Artifact.git`
2. Ran the command `docker-compose up --build -d`

**Environment**: Microsoft Windows 10 Home

**Severity**: Medium
**Priority**: High

**Comment by SEsseltine** [comment]
this seems to be a machine-specific issue and should not be encountered in production
