### ISSUE TITLE
Console warning on Interval Prediction page

### ISSUE THREAD

**Issue by myrithok** [TriageCapacityPlanning/Testable-Artifiact#33]
**Description:** Loading the the **Interval Prediction** page produces the following console warning:

![image](https://user-images.githubusercontent.com/32877366/110266071-0e2ddb00-7f8b-11eb-82b1-5ec4d0abb3d2.png)

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Navigate to **Interval Prediction**

**Comment by SEsseltine** [comment]
This has been corrected in the new UI
