### ISSUE TITLE
Console error on Interval Prediction page

### ISSUE THREAD

**Issue by myrithok** [TriageCapacityPlanning/Testable-Artifiact#34]
**Description:** Loading the the **Interval Prediction** page produces the following console error:

![image](https://user-images.githubusercontent.com/32877366/110266169-40d7d380-7f8b-11eb-809d-6b3ca36259a0.png)

**Severity:** Medium

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Navigate to **Interval Prediction**

**Comment by SEsseltine** [comment]
same error as #33
