### ISSUE TITLE
Empty form can be submitted, and produces console error

### ISSUE THREAD

**Issue by myrithok** [TriageCapacityPlanning/Testable-Artifiact#35]
**Description:** The **Interval Prediction** page allows the submission of a completely empty form:

![image](https://user-images.githubusercontent.com/32877366/110266461-d6736300-7f8b-11eb-8efd-904d1516ee8b.png)

Doing so gives no feedback to the user whatsoever, and produces the following console error:

![image](https://user-images.githubusercontent.com/32877366/110266497-ebe88d00-7f8b-11eb-9cbc-3b274393f406.png)

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Navigate to **Interval Prediction**
- Click the **Get Prediction** button

**Comment by SEsseltine** [comment]
duplicate #22
