### ISSUE TITLE
Number of simulations identifies 0 as negative

### ISSUE THREAD

**Issue by myrithok** [TriageCapacityPlanning/Testable-Artifiact#36]
**Description:** The **Number of simulations** field on the interval prediction page does not accept 0, even though the instruction text suggests that 0-100 is acceptable. In addition, it flags 0 as a negative number:

![image](https://user-images.githubusercontent.com/32877366/110266800-982a7380-7f8c-11eb-8562-ad6ab8216cad.png)

**Severity:** Medium

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Navigate to **Interval Prediction**
- Enter 0 into the **Number of simulations** field

**Comment by SEsseltine** [comment]
fixed, field has been removed
