### ISSUE TITLE
Interval prediction allows a decimal number of simulations

### ISSUE THREAD

**Issue by myrithok** [TriageCapacityPlanning/Testable-Artifiact#37]
**Description:** The **Number of simulations** field on the **Interval Prediction** page accepts a decimal number of simulations. This seems unintended, as running half of a simulations does not make sense. **Prediction Results** are still produced:

![image](https://user-images.githubusercontent.com/32877366/110267254-682fa000-7f8d-11eb-8300-e541fde65ed3.png)

But a console error is also produced:

![image](https://user-images.githubusercontent.com/32877366/110267313-872e3200-7f8d-11eb-856d-e89a127572ac.png)

**Severity:** Medium

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Navigate to **Interval Prediction**
- Enter a correct **Interval** and **Confidence-level**
- Enter a decimal **Number of simulations**
- Click **Get Prediction**

**Comment by SEsseltine** [comment]
fixed with removal of field
