### ISSUE TITLE
Date picker on Interval Prediction page allows infinitely distant dates

### ISSUE THREAD

**Issue by myrithok** [TriageCapacityPlanning/Testable-Artifiact#38]
**Description:** The **Prediction Intervals** date picker on the **Interval Prediction** page allows the user to scroll infinitely far forwards or backwards. Once you reach the year 0, the years begin counting back up, despite not denoting *B.C.E.* in the field when selected:

![image](https://user-images.githubusercontent.com/32877366/110268211-4df6c180-7f8f-11eb-87b7-97edcd72185b.png)

![image](https://user-images.githubusercontent.com/32877366/110268219-53540c00-7f8f-11eb-807b-d5372e9b7b1c.png)

![image](https://user-images.githubusercontent.com/32877366/110268239-58b15680-7f8f-11eb-9bbf-aa767adff4f6.png)

However, scrolling forward does not appear to have a limit:

![image](https://user-images.githubusercontent.com/32877366/110268457-a9c14a80-7f8f-11eb-9187-ee07f499889a.png)

Furthermore, this allows the user to select an infinitely large interval:

![image](https://user-images.githubusercontent.com/32877366/110268676-13415900-7f90-11eb-9d36-a1171fdd001e.png)

![image](https://user-images.githubusercontent.com/32877366/110268690-1a686700-7f90-11eb-96e7-c5be8384b29c.png)

Submitting such an interval does product **Prediction Results**, but the results seem to have dates unrelated to the selected interval:

![image](https://user-images.githubusercontent.com/32877366/110268885-7632f000-7f90-11eb-8e62-a506a04c3951.png)

And this submission is accompanied by two console errors:

![image](https://user-images.githubusercontent.com/32877366/110268785-471c7e80-7f90-11eb-9a4e-d65eadbb8fa0.png)

![image](https://user-images.githubusercontent.com/32877366/110268807-500d5000-7f90-11eb-9def-f96af14af05a.png)

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Navigate to **Interval Prediction**
- Open the **Prediction Intervals** date picker
- Scroll infinitely far forward or backward

**Comment by SEsseltine** [comment]
@Rubinstd I believe this is likely beyond the scope as we don't know how far in the future a user would like to predict.

**Comment by SEsseltine** [comment]
> @Rubinstd I believe this is likely beyond the scope as we don't know how far in the future a user would like to predict.

If you'd like we can move to Triage-Frontend for a possible future enhancement with more research from the customer in the future?

**Comment by Rubinstd** [comment]
This is currently out of scope for the project as the prediction requirements from the client are still in development. Once the client is aware of their prediction needs then the date picker can be limited.
