### ISSUE TITLE
Prediction Parameters scroll bars are partially hidden

### ISSUE THREAD

**Issue by myrithok** [TriageCapacityPlanning/Testable-Artifiact#39]
**Description:** The scroll bar for the **Prediction Intervals** section of the **Prediction Parameters** on the **Interval Prediction** page not sized correctly for the page element:

![image](https://user-images.githubusercontent.com/32877366/110269449-c1013780-7f91-11eb-9f8d-6be51376a3b1.png)

This seems to be independent of the size of the window.
This is also true of the scroll bar for the section containing **Confidence-level** and **Number of simulations**:

![image](https://user-images.githubusercontent.com/32877366/110269527-eee67c00-7f91-11eb-878a-aa4e33e3ce27.png)

This scroll bar is not even necessary if both fields are visible.

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Navigate to **Interval Prediction**

**Comment by SEsseltine** [comment]
fixed
