### ISSUE TITLE
When "Save" clicked there should be feedback

### ISSUE THREAD

**Issue by mudarthc** [TriageCapacityPlanning/Testable-Artifiact#4]
**Issue** : when save icon is clicked on Triage Classes there is no notification if this action was a success or not 

**Steps**: 1. Go to Triage Class 2. Edit Cell 3. Click Save 

**Environment**: MAcOS

**Expected**:  expected feedback

**Actual**: no notification received, for the user it is confusing as they dont know if their action worked or not. the same feedback is received when save is not clicked. Even though function works fine a UI improvement will help the end user. for example https://material-ui.com/components/snackbars/

**Comment by SEsseltine** [comment]
User feedback provided with added snackbar
