### ISSUE TITLE
Two sections of Interval Prediction page named "Prediction Parameters"

### ISSUE THREAD

**Issue by myrithok** [TriageCapacityPlanning/Testable-Artifiact#40]
**Description:** Two elements on the **Interval Prediction** page are named **Prediction Parameters**:

![image](https://user-images.githubusercontent.com/32877366/110269728-513f7c80-7f92-11eb-9193-1d83474637bd.png)

This is not a significant issue, but it would probably be best if these had different names.

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Navigate to **Interval Prediction**

**Comment by Rubinstd** [comment]
These labels have been renamed to properly describe the inputs below.
