### ISSUE TITLE
Minor inconsistency in style of Prediction Parameters and Prediction Results elements on Interval Prediction page

### ISSUE THREAD

**Issue by myrithok** [TriageCapacityPlanning/Testable-Artifiact#41]
**Description:** The **Prediction Parameters** and **Prediction Results** elements on the **Interval Prediction** page are styled slightly differently. The **Prediction Parameters** element is slightly wider than the **Prediction Results** element, and the **Prediction Parameters** element is collapsible, while the **Prediction Results** element is not:

![image](https://user-images.githubusercontent.com/32877366/110271397-f1e36b80-7f95-11eb-9e92-60f9dde26ba3.png)

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Navigate to **Interval Prediction**

**Comment by SEsseltine** [comment]
fixed
