### ISSUE TITLE
No way to delete individual intervals in Prediction Intervals list

### ISSUE THREAD

**Issue by myrithok** [TriageCapacityPlanning/Testable-Artifiact#42]
**Description:** The **Prediction Intervals** section allows the creation of new intervals, and deletion of all created intervals, but not way to delete individual intervals.

![image](https://user-images.githubusercontent.com/32877366/110271700-8fd73600-7f96-11eb-9414-914ce96025cd.png)

This means that if you are adding multiple intervals and accidentally add one too many, your only option is to clear them all and start again. Ideally, the user should be able to simply delete the excess interval in that case.

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Navigate to **Interval Prediction**
- Click the **Add Intervals** button multiple times

**Comment by Rubinstd** [comment]
The new interval options fix this issue
