### ISSUE TITLE
Triage header directs to empty page

### ISSUE THREAD

**Issue by myrithok** [TriageCapacityPlanning/Testable-Artifiact#43]
**Description:** The **TRIAGE** title at the top of the menu on the left-hand side is a link that directs to an empty page when clicked:

![image](https://user-images.githubusercontent.com/32877366/110272036-34597800-7f97-11eb-84c1-a135d9f8f67c.png)

![image](https://user-images.githubusercontent.com/32877366/110272049-3de2e000-7f97-11eb-9d2e-0c4680a49532.png)

**Severity:** Medium

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Click on the **TRIAGE** title at the top of the menu on the left-hand side

**Comment by SEsseltine** [comment]
Same as #14
