### ISSUE TITLE
Uploading unintended file types unhandled

### ISSUE THREAD

**Issue by myrithok** [TriageCapacityPlanning/Testable-Artifiact#44]
**Description:** Uploading any unintended file type, such as a .png or .gif, is allowed, and produces the following two console errors:

![image](https://user-images.githubusercontent.com/32877366/110272466-4a1b6d00-7f98-11eb-89d7-64a554cf1e33.png)

![image](https://user-images.githubusercontent.com/32877366/110272482-5273a800-7f98-11eb-8f75-bab34e3a68c2.png)

**Severity:** Low

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Navigate to **Admin: Clinic 1**
- Click **Choose File** in the **Clinic Data** section, and select a file that is an unintended type
- Click **Upload**

**Comment by SEsseltine** [comment]
fixed
