### ISSUE TITLE
Navigation menu inaccessible on mobile

### ISSUE THREAD

**Issue by myrithok** [TriageCapacityPlanning/Testable-Artifiact#47]
**Description:** The navigation menu is completely inaccessible on mobile:

![image](https://user-images.githubusercontent.com/32877366/110273761-463d1a00-7f9b-11eb-99d5-78ce929612c0.png)

This was found on both portrait and landscape orientations of every mobile format built into chrome, except for:
- iPad landscape
- iPad Pro landscape
- iPad Pro portrait

**Severity:** Medium

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Open chrome's inspector
- Click on Toggle device toolbar
- Select any of the mentioned mobile phone presets

**Comment by SEsseltine** [comment]
This has been fixed and the navbar is accessible on mobile however at this point the user is expected to be on desktop in a professional environment and thus mobile has been treated as out of scope.
