### ISSUE TITLE
Documentation page empty

### ISSUE THREAD

**Issue by myrithok** [TriageCapacityPlanning/Testable-Artifiact#48]
**Description:** The **Documentation** page is empty:

![image](https://user-images.githubusercontent.com/32877366/110274474-e6477300-7f9c-11eb-97df-6e45f23915bb.png)

**Severity:** Medium

**OS:** Windows 10 Enterprise
**Browser:** Chrome 89.0.4389.82

**Steps to Replicate:**
- Launch the webapp
- Click on **Help** at the bottom of any page

![image](https://user-images.githubusercontent.com/32877366/110274599-2f97c280-7f9d-11eb-8878-18cc6e6c27d7.png)

- Click on the **documentation** link

![image](https://user-images.githubusercontent.com/32877366/110274695-666dd880-7f9d-11eb-99c5-5561ffd65e81.png)

**Comment by SEsseltine** [comment]
Will be fixed with the addition of a help page

**Comment by SEsseltine** [comment]
fixed
