### ISSUE TITLE
Error whenever date range contains a "31st"

### ISSUE THREAD

**Issue by BryanChiu** [TriageCapacityPlanning/Testable-Artifiact#49]
Severity: High

OS: Windows 10 Home
Browser: Chrome 89.0.4389.82

Description: The following erroneous results always appear whenever a date range that contains a 31st is run
![image](https://user-images.githubusercontent.com/25440765/110279774-acc83500-7fa7-11eb-8db9-205f518551ab.png)
(always these two intervals from 2030 with the same values, and with "Low-Urgency" missing)

For example, April 1 - May 30 is fine. April 1 - May 31 fails. March 31- May 30 fails. Feb 15 - March 15 is fine, March 15 - April 15 fails.

I'm fairly certain no one else submitted this issue which leads me to believe it could be something on my end that I am unaware of. I have done `docker-compose down` and then `docker-compose up` to see if it was some complex process to reproduce, but it is as simple as selecting the mentioned date range condition.

**Comment by Rubinstd** [comment]
This bug has been fixed
