### ISSUE TITLE
Simulation input placeholder typo? 

### ISSUE THREAD

**Issue by mudarthc** [TriageCapacityPlanning/Testable-Artifiact#5]
**Bug** :  the simulation number placeholder is 1000 but the recommended is 0-100, these are two contradicting messages.
**Steps**:  
1. Go to "Interval Prediction" 
2. click " Number of simulations"
**Environment**:  MacOS
**Expected**: expected consistent numbers
**Actual**:  two differing recommendations, I assume this was a typo and you meant to have 100 and 0-100, considering in your test instruction you stated "(default is 100 and we recommend staying around this because it will take a really long time to run more)"

![Screen Shot 2021-02-25 at 1 29 50 PM](https://user-images.githubusercontent.com/35268733/109199541-916e5600-776d-11eb-973e-fdf7082e6422.png)

**Comment by SEsseltine** [comment]
fixed
