### ISSUE TITLE
Prediction result tabs should be in order set in Admin

### ISSUE THREAD

**Issue by BryanChiu** [TriageCapacityPlanning/Testable-Artifiact#50]
Severity: Low

OS: Windows 10 Home
Browser: Chrome 89.0.4389.82

Description: The tabs of the Prediction Results is in alphabetical order, but should probably be in the order set in Admin.
![image](https://user-images.githubusercontent.com/25440765/110280954-beaad780-7fa9-11eb-9500-cd4318dd2f03.png)

**Comment by SEsseltine** [comment]
fixed with new table implementation by @Rubinstd
