### ISSUE TITLE
An error shows up after following README.md

### ISSUE THREAD

**Issue by leon1213** [TriageCapacityPlanning/Testable-Artifiact#52]
![image](https://user-images.githubusercontent.com/48035126/110308334-f3b33a80-803a-11eb-85bf-bf2c23fc1545.png)
![image](https://user-images.githubusercontent.com/48035126/110308356-f9a91b80-803a-11eb-9327-ba0653a9c718.png)

After executing the highlighted command, an error shows up as the second screenshot tells.

**Comment by SEsseltine** [comment]
The docker-compose wasn't run within the cloned repository
