### ISSUE TITLE
Prediction Interval "Clear All" button misleading UX

### ISSUE THREAD

**Issue by anthonylou** [TriageCapacityPlanning/Testable-Artifiact#53]
The symbols used for "Add Interval" and "Clear All Intervals" are potentially misleading:
![Screenshot 2021-03-08 071357](https://user-images.githubusercontent.com/48287641/110320289-0ea39180-7fde-11eb-890a-67dde94469db.png)

Due to the behaviour of the `+` symbol adding a single interval, as well as the symbols appearing to stay with the last interval (symbols are always at bottom of window), users are led to believe that the `x` symbol would delete the last interval. 

This can be fixed by using a clearer symbol to denote "Remove all entries", or by adding a "Delete last entry" option.

**Comment by SEsseltine** [comment]
@Rubinstd should we add a tooltip here?

**Comment by Rubinstd** [comment]
A tooltip has been added to make the buttons function more clear.
