### ISSUE TITLE
Docker build does not run app

### ISSUE THREAD

**Issue by IndiW** [TriageCapacityPlanning/Testable-Artifiact#54]
# Severity
High

# Environment
Windows 10 Pro, Firefox

# Steps to recreate
Follow installation instructions on github.

# Expected behavior
After running docker build, should be able to run app from  http://localhost:4200/interval-prediction
# Actual Behavior
App is not running on  http://localhost:4200/interval-prediction. If additional steps are required they should be mentioned in the installation guide

![image](https://user-images.githubusercontent.com/45280177/110357291-22182200-8009-11eb-9d55-8759732161e2.png)

![image](https://user-images.githubusercontent.com/45280177/110357261-1a587d80-8009-11eb-95a0-a4ff1ea57fa2.png)

**Comment by SEsseltine** [comment]
This seems to be a specific docker issue for your machine. This shouldn't cause problems in production.
