### ISSUE TITLE
App on docker immediately stops after build.

### ISSUE THREAD

**Issue by IndiW** [TriageCapacityPlanning/Testable-Artifiact#55]
# Severity
High

# Environment
Windows 10 Pro, Firefox

# Steps to recreate
Run docker-compose up --build -d

# Expected behavior
App stays running until it is exited

# Actual Behavior
The app exits immediately with the following error in docker:

![image](https://user-images.githubusercontent.com/45280177/110358073-f8abc600-8009-11eb-8d15-8fe77ef733f5.png)

**Comment by SEsseltine** [comment]
This seems to be a specific docker issue for your machine. This shouldn't cause problems in production.
