### ISSUE TITLE
Api request issue? status "invalid"

### ISSUE THREAD

**Issue by mudarthc** [TriageCapacityPlanning/Testable-Artifiact#6]
**Bug** :  upon "get prediction" clicked a console log of status invalid appears, it takes a few tries for the data to appear

**Steps**:  
1. go to Admin
2.   Click upload data and upload sample data
3.  go to "interval prediction"
4.  input date range (2 weeks), CI : 95, # simulations: 50 
5.  click "get prediction"

**Environment**:  mac os

**Expected**:  data to appear after 1 click, no invalid console log

**Actual**:  "invalid" console log appeared immediately after clicking "get prediction"

![Screen Shot 2021-02-25 at 1 45 26 PM](https://user-images.githubusercontent.com/35268733/109201382-c7143e80-776f-11eb-8e25-fcc0afb8f19f.png)

**Comment by Rubinstd** [comment]
This bug has been fixed

**Comment by Rubinstd** [comment]
This bug has been fixed
