### ISSUE TITLE
Prediction interval more options required 

### ISSUE THREAD

**Issue by mudarthc** [TriageCapacityPlanning/Testable-Artifiact#7]
**Bug** :  when another predicted interval is added (refer to first image), the add and delete options are not longer available (refer to second image)
**Steps**: 
 1. go to http://localhost:4200/interval-prediction 
 2. select first prediction interval 
 3. click "+" 
 4. select another prediction interval 
 5. notice that options to delete an interval or add another on do not exist

**Environment**: Mac OS

**Expected**:  expected consistent functionality when second parameter added

**Actual**: functionality and buttons disappear on second parameter 

![Screen Shot 2021-02-25 at 1 54 16 PM](https://user-images.githubusercontent.com/35268733/109202524-1313b300-7771-11eb-91e7-67b9c9ba09fe.png)
![Screen Shot 2021-02-25 at 1 54 46 PM](https://user-images.githubusercontent.com/35268733/109202526-13ac4980-7771-11eb-9144-f29f3dedb652.png)

**Comment by SEsseltine** [comment]
fixed
