### ISSUE TITLE
The loading time for `Triage website` is super long? Maybe add a notice

### ISSUE THREAD

**Issue by lim147** [TriageCapacityPlanning/Testable-Artifiact#9]
The loading time for opening `http://localhost:4200/interval-prediction` is more than 1 min on my machine, thus I closed it and rebuild the server several times as I thought it was not built successfully.  Maybe add a notice on the testable artifact to avoid this confision.

**Comment by SEsseltine** [comment]
Seems this issue may be machine specific and will not apply to deployment anyways.
